### ISSUE TITLE
Promote Federico to the next level of member

### ISSUE THREAD

**Issue by polespinasa** [Bitcoin-GroupHug/grouphug-client#15]
I lack some features in Project Management. I do not need owner.

**Comment by polespinasa** [comment]
Role changed from Collaborator to Admin in the Grouphug-Client repo. @federicociro please close the issue if it's enough.

**Comment by federicociro** [comment]
Thank you. Another issue opened at 

- [ ] Change project visibility to Public

as only the owner of the organization can perform this task.
